Update tf-unit-tests.yml

diff --git a/.github/workflows/tf-unit-tests.yml b/.github/workflows/tf-unit-tests.yml
--- a/.github/workflows/tf-unit-tests.yml
+++ b/.github/workflows/tf-unit-tests.yml
@@ -101,6 +101,13 @@ jobs:
     - name: Terraform Format Pass Check
       if: steps.fmt_check.outcome == 'success'
       run: echo "Terraform formatting is correct. Proceeding to security scan..."
+
+    # Ensures changes after code formatting fail the action so a PR cannot be merged without human verification
+    - name: Fail if Auto Format Ran
+      if: failure() && steps.fmt_check.outcome == 'failure'
+      run: |
+        echo "Auto-formatting was required. Please review and re-run the workflow."
+        exit 1
     
     # Perform a security scan of the terraform code using checkov
     - name: Run Checkov action
